apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: likhithabhogyam/appointment-service:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: appointment-service-config
        - secretRef:
            name: appointment-service-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
        readinessProbe:
          httpGet:
            path: /
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 20